name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  myci:
    # 运行环境
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # go 的环境
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    # 编译
    - name: Build
      run: go build -v ./...
    # 风格检查
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

    - name: Test
      run: go test -v ./...